export const colors = {
  bg:            '#FFFFFF',
  surface:       '#F5F7FA',
  border:        '#E5E7EB',
  accent:        '#0066FF',
  accentSoft:    '#EBF2FF',
  accentPress:   '#0052CC',
  textPrimary:   '#0A0A0F',
  textSecondary: '#6B7280',
  textMuted:     '#9CA3AF',
  textInverse:   '#FFFFFF',
  success:       '#00C9A7',
  successBg:     '#E6FAF7',
  warning:       '#F59E0B',
  warningBg:     '#FEF9EC',
  error:         '#EF4444',
  errorBg:       '#FEF2F2',
  like:          '#EF4444',
  online:        '#00C9A7',
  codeBg:        '#1E1E2E',
} as const
